#!/bin/zsh

# Environment variables

export SHARE_HISTORY=true
export HISTORY_IGNORE='(fg|ll|jobs|cd|j|l|exit)'

export TERM=xterm-24bit
export EMACS="*term*"
export EDITOR=emacs
export PAGER=less
export LESS=-RFiX

# Important for direnv
export XDG_DATA_HOME=/Users/ashton/.config
